#!D:\WebWAPM\XAMPP\perl\bin\perl.exe 
print "Content-type: text/html; charset=GB2312\n\n";
$a[0] = 'bedr';
$a[1] = 'slat';
$a[2] = 'lava';
$a[3] = '3lava';
$a[4] = '4ccclava';
$a[5] = '5ccclava';
#$a[222] = '5ccclava';
print "$a[-1]  <br>";
print "aa <br>";
print "$a[-220] ww  <br>";
print "bb <br>";
print "bb <br>";
print "bb <br>";
print "bb <br>";
print "$a[3] <br>";
print "bb <br>";
print "bb <br>";
print "bb <br>";
